[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v
markers =
    smoke: pruebas criticas de humo
    login: pruebas de inicio de sesion
    catalogo: pruebas del inventario/catalogo
    carrito: pruebas del carrito de compras
